export const PROJECTDATA = [
  {
    title: "Anime Memory Game",
    img: "/projects/amg.png",
    desc: "Test your anime knowledge and memory skills with an engaging Anime Memory Game.",
    website: "https://anime-memory-game-hriday.vercel.app/",
    code: "https://github.com/Hriday2406/memory-game",
    tech: ["React", "Tailwind", "Git"],
  },
  {
    title: "CV Builder",
    img: "/projects/cv.png",
    desc: "Create a professional CV effortlessly with online CV builder.",
    website: "https://cv-builder-three.vercel.app/",
    code: "https://github.com/Hriday2406/CV-Builder",
    tech: ["React", "Git"],
  },
  {
    title: "To-Do List",
    img: "/projects/todo.png",
    desc: "A simple and intuitive web app to create, organize, and manage your daily tasks.",
    website: "https://hriday2406.github.io/to-do-list/",
    code: "https://github.com/Hriday2406/to-do-list",
    tech: ["HTML5", "CSS3", "Js", "Git"],
  },
  {
    title: "Mausam",
    img: "/projects/mausam.png",
    desc: "Get real-time weather updates with our Weather App.",
    website: "https://hriday2406.github.io/mausam/",
    code: "https://github.com/Hriday2406/mausam",
    tech: ["HTML5", "CSS3", "Js", "Git"],
  },
  {
    title: "Calculator",
    img: "/projects/calc.png",
    desc: "A fast, elegant and easy-to-use calculator for all your calculation needs.",
    website: "https://hriday2406.github.io/Calculator/",
    code: "https://github.com/Hriday2406/Calculator",
    tech: ["HTML5", "CSS3", "Js", "Git"],
  },
  {
    title: "Tic Tac Toe",
    img: "/projects/tictactoe.png",
    desc: "Play the classic Tic-Tac-Toe game online! Challenge a friend and see whose better.",
    website: "https://hriday2406.github.io/tic-tac-toe/",
    code: "https://github.com/Hriday2406/tic-tac-toe",
    tech: ["HTML5", "CSS3", "Js", "Git"],
  },
  {
    title: "Etch-a-Sketch",
    img: "/projects/etch.png",
    desc: "Experience the nostalgia of the classic Etch-a-Sketch with our web-based drawing app.",
    website: "https://hriday2406.github.io/Etch-a-Sketch/",
    code: "https://github.com/Hriday2406/Etch-a-Sketch",
    tech: ["HTML5", "CSS3", "Js", "Git"],
  },
  {
    title: "Admin Panel Frontend",
    img: "/projects/admin.png",
    desc: "An Admin panel offers an interface for managing website content, user profiles, and settings.",
    website: "https://hriday2406.github.io/admin-dashboard/",
    code: "https://github.com/Hriday2406/admin-dashboard",
    tech: ["HTML5", "CSS3", "Js", "Git"],
  },
];
