export const PROJECTDATA = [
  {
    title: "Inventory Application",
    img: "/projects/inventory.webp",
    desc: "Item tracking website for efficient inventory management.",
    website: "https://inventory-application-cir4.onrender.com/",
    code: "https://github.com/Hriday2406/inventory-application",
    tech: ["NodeJs", "ExpressJs", "PostgreSQL", "Tailwind", "Git"],
  },
  {
    title: "Mini Message Board",
    img: "/projects/mini-message.webp",
    desc: "A simple and user-friendly message board where users can post their thoughts and comments.",
    website: "https://mini-message-board-ebpu.onrender.com/",
    code: "https://github.com/Hriday2406/mini-message-board",
    tech: ["NodeJs", "ExpressJs", "PostgreSQL", "Tailwind", "Git"],
  },
  {
    title: "Fruits Lelo",
    img: "/projects/fruits.webp",
    desc: "An e-commerce website having minimilist design and user friendly interface.",
    website: "https://fruits-lelo.vercel.app/",
    code: "https://github.com/Hriday2406/fruits-lelo",
    tech: ["React", "Tailwind", "Git"],
  },
  {
    title: "Anime Memory Game",
    img: "/projects/amg.webp",
    desc: "Test your anime knowledge and memory skills with an engaging Anime Memory Game.",
    website: "https://anime-memory-game-hriday.vercel.app/",
    code: "https://github.com/Hriday2406/memory-game",
    tech: ["React", "Tailwind", "Git"],
  },
  {
    title: "CV Builder",
    img: "/projects/cv.webp",
    desc: "Create a professional CV effortlessly with online CV builder.",
    website: "https://cv-builder-three.vercel.app/",
    code: "https://github.com/Hriday2406/CV-Builder",
    tech: ["React", "Git"],
  },
  {
    title: "To-Do List",
    img: "/projects/todo.webp",
    desc: "A simple and intuitive web app to create, organize, and manage your daily tasks.",
    website: "https://hriday2406.github.io/to-do-list/",
    code: "https://github.com/Hriday2406/to-do-list",
    tech: ["HTML5", "CSS3", "Js", "Git"],
  },
  {
    title: "Mausam",
    img: "/projects/mausam.webp",
    desc: "Get real-time weather updates with our Weather App.",
    website: "https://hriday2406.github.io/mausam/",
    code: "https://github.com/Hriday2406/mausam",
    tech: ["HTML5", "CSS3", "Js", "Git"],
  },
  {
    title: "Calculator",
    img: "/projects/calc.webp",
    desc: "A fast, elegant and easy-to-use calculator for all your calculation needs.",
    website: "https://hriday2406.github.io/Calculator/",
    code: "https://github.com/Hriday2406/Calculator",
    tech: ["HTML5", "CSS3", "Js", "Git"],
  },
];
